export default class Constants {
    static readonly PLUGIN_NAME = "acu-pack";
    static readonly DEFAULT_XML_NAMESPACE = "http://soap.sforce.com/2006/04/metadata";
    static readonly METADATA_COVERAGE_REPORT_URL = "https://dx-extended-coverage.my.salesforce-sites.com/services/apexrest/report";
    static readonly DEFAULT_PACKAGE_NAME = "package.xml";
    static readonly DEFAULT_PACKAGE_PATH: string;
    static readonly SFDX_DESCRIBE_METADATA = "sfdx force:mdapi:describemetadata";
    static readonly SFDX_APEX_EXECUTE = "sfdx force:apex:execute";
    static readonly SFDX_SOURCE_RETRIEVE = "sfdx force:source:retrieve";
    static readonly SFDX_PROJECT_CREATE = "sfdx force:project:create";
    static readonly SFDX_MDAPI_LISTMETADATA = "sfdx force:mdapi:listmetadata";
    static readonly SFDX_SCHEMA_DESCRIBE = "sfdx force:schema:sobject:describe";
    static readonly SFDX_DATA_UPSERT = "sfdx force:data:bulk:upsert";
    static readonly SFDX_DATA_STATUS = "sfdx force:data:bulk:status";
    static readonly SFDX_ORG_DISPLAY = "sfdx force:org:display";
    static readonly SFDX_SOURCE_STATUS = "sfdx force:source:status";
    static readonly SFDX_CONFIG_GET = "sfdx config:get";
    static readonly SFDX_CONFIG_SET = "sfdx config:set";
    static readonly SFDX_CONFIG_DEFAULT_USERNAME = "defaultusername";
    static readonly SFDX_CONFIG_MAX_QUERY_LIMIT = "maxQueryLimit";
    static readonly SFDX_PERMISSION_APEX_CLASS = "ApexClass";
    static readonly SFDX_PERMISSION_APEX_PAGE = "ApexPage";
    static readonly SFDX_PERMISSION_CUSTOM_APP = "CustomApplication";
    static readonly SFDX_PERMISSION_CUSTOM_OBJ = "CustomObject";
    static readonly SFDX_PERMISSION_CUSTOM_FIELD = "CustomField";
    static readonly SFDX_PERMISSION_CUSTOM_TAB = "CustomTab";
    static readonly SFDX_PERMISSION_SET = "PermissionSet";
    static readonly SFDX_PERMISSION_PROFILE = "Profile";
    static readonly SFDX_PERMISSION_RECORD_TYPE = "RecordType";
    static readonly SFDX_PERMISSION_LAYOUT = "Layout";
    static readonly SFDX_DATA_QUERY = "sfdx force:data:soql:query";
    static readonly DEFAULT_PROJECT_FILE_NAME = "sfdx-project.json";
    static readonly DEFAULT_SFDC_LOGIN_URL = "https://login.salesforce.com";
    static readonly DEFAULT_PACKAGE_VERSION = "49.0";
    static readonly ENOENT = "ENOENT";
    static readonly CONTENT_TYPE_APPLICATION = "application/octetstream";
    static readonly HEADERS_CONTENT_TYPE = "content-type";
    static readonly METADATA_FILE_SUFFIX = "-meta.xml";
    static readonly HTTP_STATUS_REDIRECT: number[];
}
