# This workflow will run tests using node
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Validate npm package

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Run Tests
        run: |
          yarn install --frozen-lockfile
          yarn add sfdx-cli
          yarn run testn
          npm publish --dry-run

